### ISSUE TITLE
Is there a creole-mode?

### ISSUE THREAD

**Issue by bluemont** [nicferrier/elwikicreole#10]
Hello, thanks for sharing this code. I'm relatively new to emacs, but I'm curious enough to go searching for new modes. That is why I looked for and found your project here. I was hoping to find a major mode called `creole-mode` defined that gave syntax highlighting and so on. I was expecting to find something like the following defined in a `creole-mode.el` file:

```
(autoload 'creole-mode "creole-mode.el" "Major mode for editing Creole Wiki files" t)
(setq auto-mode-alist (cons '("\\.wiki" . creole-mode) auto-mode-alist))
```

Do you use Creole in some other way?

See also: http://manuelp.github.com/emacs/2009/11/03/wikicreole-mode-emacs.html

**Comment by nicferrier** [comment]
creole.el is not a creole-mode, no. It's a creole parser written in EmacsLisp. It can be combined with elnode (a webserver written in EmacsLisp) to provide a wiki or a blog. For example http://github.com/nicferrier/skinny is (most of) a blog engine written completly in Elisp and using creole as the blog entry format. 

I am considering writing a creole-mode and it will look something like Alex's that you linked to. It probably won't be for a while though and it's won't be part of this code.

**Comment by nicferrier** [comment]
Actually, I made this: https://github.com/nicferrier/creole-mode

**Comment by bluemont** [comment]
Thanks!
